### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by akshayweb** [Prezent/jquery-weekpicker#1]
Its not working can you recheck it and please put full code with html

now i am using 

<script type="text/javascript">
$('input.weekpicker').each(function (i, el) {
    $(el).weekpicker({
        firstDay: 1,
        startField: el
    });
});
</script>

<input type="text" id="selector" class="weekpicker" />

may be i miss something please correct me 
thanks

**Comment by wondie** [comment]
I also have the same comment. Example with html or a demo page will be very useful and more people will definitely be interested in it. Including me.

**Comment by akshayweb** [comment]
may be it will help you http://jsfiddle.net/manishma/AVZJh/light/

Thanks

**Comment by wondie** [comment]
The problem with that demo is it gives range of dates for a given week. I want something like HTML5 like week picker which outputs YYYYWww or  (2015W15).

**Comment by sandermarechal** [comment]
The weekpicker is an extension of the standard datepicker. In order to output week numbers, jQuery UI's `formatDate` itself would need to support weeknumbers: http://api.jqueryui.com/datepicker/#utility-formatDate
