### ISSUE TITLE
Small fix when using alongside normal datepickers

### ISSUE THREAD

**Issue by sambruggeman** [Prezent/jquery-weekpicker#10]
The ui-state-hover is triggered on my default datepickers, with this little piece of code they keep on working as intended.. :) thanks for the plugin mate!
`$dp.on('mousemove', '.ui-datepicker-calendar tr', function () {
                        if ($(this).parents('.ui-weekpicker').length) {
                            $(this).find('td a').addClass('ui-state-hover');
                        }
                    });
`

**Comment by sandermarechal** [comment]
I'm afraid I don't understand what your original issue is. Could you describe it in a bit more dertail? Or perhaps create a JSFiddle showing the problem?

**Comment by sambruggeman** [comment]
I was somewhat in a hurry this morning, apologies. What I'm having is that default datepickers running side-by-side with your weekpicker also get the entire week in 'ui-state-hover', not only the day.  (and this only after the first time you open the weekpicker dialog.)

http://jsfiddle.net/ovek/d0a8cg1g/3/

The little if-statement added to the area where the hover-state is defined should sort it out.

**Comment by sandermarechal** [comment]
Ah, now I understand. Fixed, thanks!
