### ISSUE TITLE
Multiple Week

### ISSUE THREAD

**Issue by iwoanton** [Prezent/jquery-weekpicker#11]
Hi all,
Any idea how to do multiple week selection?? In advance say i using for a booking system of houses.

It has to be appreciated that a week can already be reserved so the multiple weeks must be consecutive, if I want to make a multiple booking from 09-01-2017 to 29-01-2017 if from 23-01-2017 to 29 -01-2017 I already have a reservation you could only select from 09-01-2017 to 01-22-2017

The already created reservations are already blocked in the calendar, what I need is to be able to do multiple week selection

Thanks in advance

**Comment by sandermarechal** [comment]
I think you would be better off customizing the datepicker yourself. Your use case is quite specific and doesn't really fit into the weekpicker. Or maybe even better, use a date *range* picker: http://www.daterangepicker.com/

**Comment by iwoanton** [comment]
Thanks a lot! Very useful
