### ISSUE TITLE
Not allowed to load local resource:

### ISSUE THREAD

**Issue by gregoryca** [Prezent/jquery-weekpicker#12]
Hi, i'm using your plugin to create a weekbased calendar. but i stumbled op on a problem.

as soon as i include the location of the script within the <script> tags, chrome blocks the script from loading. it's for an application, that intergrates a week based calendar. thank you for your help

**Comment by sandermarechal** [comment]
This has nothing to do with the weekpicker itself. You should probably have a look at your [Content Security Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) settings. That is probably what is prevening the script from loading.
