### ISSUE TITLE
Error when startField is set

### ISSUE THREAD

**Issue by Kiranbhat2005** [Prezent/jquery-weekpicker#4]
Hi,

  The plug in is really useful and exactly what I was looking for. 

  I am facing an issue with the weekpicker. When startField is set, I get an error on line 215 (line 225 if endField is set) saying 'input' not defined.

Please look into the issue and let me know the solution.

Here is my code.

  $(document).ready(function() {
            $('.x').each(function (i, el) {
                $(el).weekpicker({
                    weekLength: 5,
                    showWeek: true,
                     maxDate: "+0D",
                     format: "dd M yyyy",
                     todayHighlight: true,
                     startField: $('#result')
                });
            });
        });

 <input type="text" id="txt_date" class="x" value="">
 <input type="text" id="result"   value="result appears here">

**Comment by sandermarechal** [comment]
Should be fixed now

**Comment by Kiranbhat2005** [comment]
Yes, it works fine now! Thank you so much :)
