### ISSUE TITLE
Inital end date value is wrong

### ISSUE THREAD

**Issue by prolic** [Prezent/jquery-weekpicker#6]
I have this:

```
$('#datepicker_end').weekpicker({
    endField: '#datepicker_end',
    dateFormat: 'yy-mm-dd',
    minDate: 48 - weekDay,
    inline: true,
    altField: "#end_hidden"
});
```

And the end_hidden is populated with begin, instead of end for the start. When i click on some date, the correct end_hidden is populated. But the initial one is false.

I had to put this

```
var date = new Date($('#end_hidden').val());
date.setDate(date.getDate() + 6);
$('#end_hidden').val(date.toISOString().substring(0, 10));
```

at the end of my code to have to correct end_hidden value populated initiallly.

**Comment by sandermarechal** [comment]
The weekpicker doesn't do anything with the altField. The contents of the altField are whatever day you click on when selecting the week. The endField isn't populated until you pick a date.
